### ISSUE TITLE
 "parameterBitLength" is null

### ISSUE THREAD

**Issue by JorisVanEijden** [OpenRakis/spice86-ghidra-plugin#5]
```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "parameterBitLength" is null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "parameterBitLength" is null
	at spice86.tools.Spice86Task.run(Spice86Task.java:42)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "parameterBitLength" is null
	at spice86.generator.parsing.ParsedInstructionBuilder.isParameterModified(ParsedInstructionBuilder.java:231)
	at spice86.generator.parsing.ParsedInstructionBuilder.completeWithSelfModifyingCodeInformation(ParsedInstructionBuilder.java:201)
	at spice86.generator.parsing.ParsedProgramBuilder.registerModifiedInstructions(ParsedProgramBuilder.java:187)
	at spice86.generator.parsing.ParsedProgramBuilder.createParsedProgram(ParsedProgramBuilder.java:45)
	at spice86.generator.Spice86CodeGeneratorTask.runWithContextAndConfiguration(Spice86CodeGeneratorTask.java:48)
	at spice86.tools.Spice86Task.run(Spice86Task.java:40)
	... 5 more
```
I'm not sure which address/opcode this occurs because that isn't logged.

But I suspect it's opcode 0x99 (CDW) or its prefixed variant 0x66 0x99 (CDQ).
That exists in a 16 and a 32 bits variant but takes no parameters at all.

**Comment by kevinferrare** [comment]
This is being fixed as well, was caused by the changes to adapt the generator to the 32bits changes done on spice86.
